CREATE TABLE IF NOT EXISTS posts (

    -- PRIMARY FIELDS
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    description TEXT NOT NULL,
    photo_link VARCHAR,
    video_link VARCHAR,
    private BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    likes BIGINT DEFAULT 0,

    -- AUDIT FIELDS
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

);

-- INDEXES
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_posts_active ON posts(deleted) WHERE deleted = false;
CREATE INDEX idx_posts_deleted ON posts(deleted) WHERE deleted = true;
CREATE INDEX idx_feed_posts ON posts(private, deleted) WHERE private = false AND deleted = false;
