spring:
  application:
    name: "teachgram_back"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    expiration: ${JWT_EXPIRATION}
    token-prefix: ${JWT_TOKEN_PREFIX}